spring.application.name=travel_plan

# Replace localhost connection with Aiven's connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# ? Amadeus API credentials
amadeus.api.key={$amadeus_key}
amadeus.api.secret={$amadeus_sec}

rapidapi.key={$rapid}

openweather.api.key={$open}
openweather.api.geocoding-url={$open_geourl}
openweather.api.weather-url={$openurl}

unsplash.api.key={$unsplash}

# Foursquare API Key
foursquare.api.key={$foursquare}
